In [ ]:
import functools
import json
import math
import pandas as pd
import pennylane as qml
import pennylane.numpy as np
import scipy

def circuit():
    """
    Succession of gates that will generate the requested matrix.
    This function does not receive any arguments nor does it return any values.
    """

    # Put your solution here ...
    # You only have to put U3 or CNOT gates


# These functions are responsible for testing the solution.

def run(input: str) -> str:
    matrix = qml.matrix(circuit)().real

    with qml.tape.QuantumTape() as tape:
        circuit()

    names = [op.name for op in tape.operations]
    return json.dumps({"matrix": matrix.tolist(), "gates": names})

def check(user_output: str, expected_output: str) -> str:
    parsed_output = json.loads(user_output)
    matrix_user = np.array(parsed_output["matrix"])
    gates = parsed_output["gates"]

    solution = (
        1
        / np.sqrt(2)
        * np.array(
            [
                [1, 1, 0, 0, 0, 0, 0, 0],
                [1, -1, 0, 0, 0, 0, 0, 0],
                [0, 0, -1, -1, 0, 0, 0, 0],
                [0, 0, -1, 1, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 0, 0],
                [0, 0, 0, 0, 1, -1, 0, 0],
                [0, 0, 0, 0, 0, 0, 1, 1],
                [0, 0, 0, 0, 0, 0, 1, -1],
            ]
        )
    )

    assert np.allclose(matrix_user, solution)
    assert len(set(gates)) == 2 and "U3" in gates and "CNOT" in gates


test_cases = [['No input', 'No output']]

for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")

In [4]:
import functools
import json
import math
import pandas as pd
import pennylane as qml
import pennylane.numpy as np
import scipy

In [328]:
def circuit():
    """
    qml.U3(np.pi,0,np.pi, wires = 0)
    qml.U3(np.pi/2,0,np.pi,wires = 1)
    qml.U3(np.pi/2,0,np.pi,wires = 2)
    qml.CNOT(wires = [0,1])
    qml.U3(np.pi,0,np.pi,wires = 0)
    qml.U3(np.pi/2,0,np.pi,wires = 1)
    """
    
    qml.U3(np.pi, 0, np.pi, wires = 0)
    qml.U3(np.pi/2,0,np.pi,wires = 1)
    #qml.U3(np.pi/2,0,np.pi,wires = 2)
    #qml.CNOT(wires = [0,1])
    #qml.U3(np.pi,0,np.pi,wires = 0)
    #qml.U3(np.pi/2,0,np.pi,wires = 1)
    
    #qml.CNOT(wires=[0,1])
    #qml.CNOT(wires=[1,0])
    #qml.CNOT(wires=[0,1])

    #qml.U3(np.pi, 0, 0, wires = 2)
    
    #qml.CNOT(wires=[1,0])
    #qml.CNOT(wires=[2,0])

    #qml.U3(-np.pi/2, 0, 0, wires = 2)
    #qml.CNOT(wires=[1,0])
    #qml.U3(-np.pi/2, 0, 0, wires = 1)
    #qml.CNOT(wires=[0,1])
    
    #qml.CNOT(wires=[1,2])
    #qml.U3(np.pi/2, np.pi/2, np.pi/2, wires = 1)
 

   
matrix = qml.matrix(circuit, wire_order=[0,1,2])()

print('\n\n'.join(['      '.join(['{0.real:1.0f}'.format(np.sqrt(2)*item) for item in row]) for row in matrix]))
print('\n')
print('\n\n'.join(['    '.join(['{0.real:1.2f}+{0.imag:1.2f}i'.format(np.sqrt(2)*item) for item in row]) for row in matrix]))

0      0      0      0      1      0      1      0

0      0      0      0      0      1      0      1

0      0      -0      0      1      0      -1      0

0      0      0      -0      0      1      0      -1

1      0      1      0      -0      0      -0      0

0      1      0      1      0      -0      0      -0

1      0      -1      0      -0      0      0      0

0      1      0      -1      0      -0      0      0


0.00+0.00i    0.00+0.00i    0.00+-0.00i    0.00+0.00i    1.00+-0.00i    0.00+0.00i    1.00+-0.00i    0.00+0.00i

0.00+0.00i    0.00+0.00i    0.00+0.00i    0.00+-0.00i    0.00+0.00i    1.00+-0.00i    0.00+0.00i    1.00+-0.00i

0.00+0.00i    0.00+0.00i    -0.00+0.00i    0.00+0.00i    1.00+-0.00i    0.00+0.00i    -1.00+0.00i    0.00+0.00i

0.00+0.00i    0.00+0.00i    0.00+0.00i    -0.00+0.00i    0.00+0.00i    1.00+-0.00i    0.00+0.00i    -1.00+0.00i

1.00+0.00i    0.00+0.00i    1.00+-0.00i    0.00+0.00i    -0.00+0.00i    0.00+0.00i    -0.00+0.00i    0.00+0.00i

0.00+0

In [37]:
print(1/np.sqrt(2))

0.7071067811865475


In [204]:
[np.cos(np.pi), np.cos(np.pi/2), np.cos(np.pi/4), np.sin(np.pi), np.sin(np.pi/2), np.sin(np.pi/4)]

[-1.0,
 6.123233995736766e-17,
 0.7071067811865477,
 1.2246467991473532e-16,
 1.0,
 0.7071067811865476]

In [84]:
qml.matrix(qml.U3(0,0,0,wires=0))

array([[ 1.+0.j, -0.+0.j],
       [ 0.+0.j,  1.+0.j]])

In [85]:
qml.matrix(qml.U3(np.pi/2,0,0,wires=0))

array([[ 0.70710678+0.j, -0.70710678+0.j],
       [ 0.70710678+0.j,  0.70710678+0.j]])

In [86]:
qml.matrix(qml.U3(np.pi,0,0,wires=0))

array([[ 6.123234e-17+0.j, -1.000000e+00+0.j],
       [ 1.000000e+00+0.j,  6.123234e-17+0.j]])

In [88]:
qml.matrix(qml.U3(0,np.pi,0,wires=0))

array([[ 1.+0.0000000e+00j, -0.+0.0000000e+00j],
       [-0.+0.0000000e+00j, -1.+1.2246468e-16j]])

In [89]:
qml.matrix(qml.U3(0,0,np.pi/2,wires=0))

array([[ 1.000000e+00+0.j, -0.000000e+00+0.j],
       [ 0.000000e+00+0.j,  6.123234e-17+1.j]])

In [90]:
qml.matrix(qml.U3(0,0,np.pi,wires=0))

array([[ 1.+0.0000000e+00j,  0.-0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])